package com.gmail.aydinov.sergey.simple_debugger_plugin.processor;

import com.gmail.aydinov.sergey.simple_debugger_plugin.event.debug_event.AbstractSimpleDebugEvent;

/**
 * Collector interface for debug events generated by the Simple Debugger.
 * Allows asynchronous collection and retrieval of debug events.
 */
public interface SimpleDebugEventCollector {

    /**
     * Collects a debug event for later processing.
     *
     * @param event the debug event to collect
     */
    void collectDebugEvent(AbstractSimpleDebugEvent event);

    /**
     * Retrieves the next debug event for processing.
     * This method blocks if no events are currently available.
     *
     * @return the next collected debug event
     * @throws InterruptedException if interrupted while waiting
     */
    AbstractSimpleDebugEvent takeDebugEvent() throws InterruptedException;
}
