package com.gmail.aydinov.sergey.simple_debugger_plugin.event.ui_event;

import com.gmail.aydinov.sergey.simple_debugger_plugin.event.SimpleDebuggerEventTypes;

/**
 * Base class for all UI events generated by user interactions.
 * <p>
 * Subclasses represent specific UI events, such as variable changes or field updates.
 * </p>
 * <p>
 * Author: Sergei Aidinov
 * <br>
 * Email: <a href="mailto:sergey.aydinov@gmail.com">sergey.aydinov@gmail.com</a>
 * </p>
 */
public abstract class AbstractSimpleDebuggerUIEvent {
	
	 private final SimpleDebuggerEventTypes.SimpleDebuggerEventType type;
		
	    public AbstractSimpleDebuggerUIEvent(SimpleDebuggerEventTypes.SimpleDebuggerEventType type) {
	        this.type = type;
	    }

	    public SimpleDebuggerEventTypes.SimpleDebuggerEventType getType() {
	        return type;
	    }
}
