package com.gmail.aydinov.sergey.simple_debugger_plugin.event.ui_event;

/**
 * Base class for all UI events generated by user interactions.
 * <p>
 * Subclasses represent specific UI events, such as variable changes or field updates.
 * </p>
 */
public abstract class AbstractUIEvent {
    // Currently no common fields or methods; serves as a marker class
}
